project:
  type: website
  output-dir: docs

website:
  title: "cycle_cities"
  navbar:
    left:
      - href: README.md
        text: Home
      - href: all_cities.html
        text: City Cycle Paths
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



